[build]
command = "cd frontend && npm run build"
publish = "frontend/build"
[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"
directory = "/backend/routes/"
[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"